
/* global constant data */
const BASE_API_HOST="BASE_API_HOST",
EVA_API_HOST=BASE_API_HOST+"eva/",
EVA_ACCESS_TOKEN="EVA_ACCESS_TOKEN",
REPO_HOST="REPO_HOST",
CORNER_HOST="CORNER_HOST",
QR_HOST="QR_HOST",
SCRIPT_HOST=BASE_API_HOST+"script/",
ONLINE_HOST=BASE_API_HOST+"online/",
FCM_KEY="FCM_KEY";


